### ISSUE TITLE
Create example resumes

### ISSUE THREAD

**Issue by marko-polo-cheno** [uwcsc/codeybot#149]
Show example resumes:
A single column
A double column
A pretty one
A bad one with a lot of text and no margins
A bad one with a lack of analytics

enum fields of CS outlined in interviewer categories

input .command field
output url(s) to drive

**Comment by mcpenguin** [comment]
I've added some resumes in the `src/resumes` folder in the `resumes` branch. I mainly just pulled some templates from Overleaf.

We should try to get some actual Waterloo resumes for examples though (upper years? internal committee? volunteers?)

**Comment by gzcharleszhang** [comment]
Let's keep this issue open until your branch gets merged, so we don't forget about it. If you want you can use my resume as an example, not sure which version you'd prefer. I have a copy of my resume from 1B to new grad.

Also, you probably don't want to keep the resume assets in `src/resumes`, maybe under `assets/resumes` or something. Since we don't know if we are going to be incorporating that into the bot yet.

**Comment by mcpenguin** [comment]
I guess you can send all your resumes (the more the merrier!) We can ask the internal committee on Discord for their resumes as well (with the personal details taken out).

**Comment by mcpenguin** [comment]
I have moved the resumes from `src` to `assets`.
